<?xml version="1.0"?>
<robot name="windshield_gripper" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <property name="gripper_base_width" value="0.07"/>
    <property name="gripper_base_length" value="0.07"/>
    <property name="gripper_base_height" value="0.01"/>

    <property name="gripper_finger_height" value="0.025"/>
    <property name="gripper_finger_length" value="0.03"/>
    <property name="gripper_finger_height" value="0.05"/>

    <material name="Black">
        <color rgba="0.15 0.15 0.15 1.0"/>
    </material>

    <xacro:macro name="windshield_gripper" params="parent name rotation">

        <!-- BASE JOINT from parent to gripper base -->
        <joint name="${parent}_${name}_base_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 ${rotation}"/>
            <parent link="${parent}"/>
            <child link="${name}_base_link"/>
        </joint>

        <!-- gripper Base link -->
        <link name="${name}_base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}" />
                </geometry>
                <material name="Black"/>
            </visual>
        </link>


        <!-- JOINT from base to left finger -->
        <joint name="${name}_base_${name}_lfinger_joint" type="fixed">
            <origin xyz="${0.5*gripper_base_length-0.5*gripper_finger_length} 0 0.025" rpy="0 0 0"/>
            <parent link="${name}_base_link"/>
            <child link="${name}_lfinger_link"/>
        </joint>

        <!-- gripper left finger link -->
        <link name="${name}_lfinger_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${gripper_finger_length} ${gripper_base_width} ${gripper_finger_height}" />
                </geometry>
                <material name="Black"/>
            </visual>
        </link>

        <!-- JOINT from base to right finger -->
        <joint name="${name}_base_${name}_rfinger_joint" type="fixed">
            <origin xyz="-${0.5*gripper_base_length-0.5*gripper_finger_length} 0 0.025" rpy="0 0 0"/>
            <parent link="${name}_base_link"/>
            <child link="${name}_rfinger_link"/>
        </joint>

        <!-- gripper right finger link -->
        <link name="${name}_rfinger_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${gripper_finger_length} ${gripper_base_width} ${gripper_finger_height}" />
                </geometry>
                <material name="Black"/>
            </visual>
        </link>


    </xacro:macro>

</robot>
